server:
  port: 8083
  tomcat:
    uri-encoding: utf-8

spring:
  servlet:
    multipart:
      max-file-size: 10MB # 限制文件上传的大小
  profiles:
    active: prod

  thymeleaf:
    cache: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  aop:
    proxy-target-class: true

  mail:
    auth: true   #开启用户名和密码认证，如果设置false，可以不设置用户名密码，要看对接平台是否支持无密码进行访问
    protocol: smtp  #以smtp服务器作为发送方式
    charset: UTF-8    #文件编码码方式
    port: 25   #   25      smtp的端口号  ×××@163.com 非 SSL 连接的端口一般默认为 25, 可以不添加, 如果开启了 SSL 连接, 需要改为对应邮箱的 SMTP 服务器的端口
    ssl: true   #是否为ssl连接
    host: smtp.exmail.qq.com   #smtp服务器地址
    timeout: 25000   #连接超时
    username: sph-kdl-qff@shaphar.com     #  sph-kdl-qff@shaphar.com    ccc032811@163.com
    password: spQff123+           #  spQff123+    ccc032811
  mvc:
    favicon:
      enabled: true
mybatis-plus:
  # 实体类扫描路径
  type-aliases-package: com.neefull.fsp.web.system.entity,com.neefull.fsp.web.generator.entity,com.neefull.fsp.web.job.entity
  # xml 扫描路径
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false


qff:
  sftps:
    sftppath:  /UploadOutbound/   # sftp文件地址
    movepath:  /UploadArchive/    #移动的目标文件
    localpath: /usr/local/files/  #文件下载到当前地址   /usr/local/files/
    host: 10.1.158.100                               #10.1.151.25
    username: QFFProd         #QFFTest
    password:  KDL@seeburger        #1qaz2wsx
  send:
    conserveTemplatePath:   #到货养护包装QFF pdf模板地址
    conserveDownLoadPath:   #到货养护包装QFF 生成的模板地址
    recentTemplatePath:     #近效期QFF pdf模板地址
    recentDownLoadPath:     #近效期QFF生成的模板地址
    refundTemplatePath:     #退货QFFpdf模板地址
    refundDownLoadPath:     #退货QFF 生成的模板地址
    rocheTemplatePath:      #罗氏内部发起QFF pdf模板地址
    rocheDownLoadPath:      #罗氏内部发起QFF 生成的模板地址
  process:
    commodityProcess: 到货养护分包出库QFF
    recentProcess: 近效期QFF
    rocheProcess: 罗氏内部发起QFF
    imagePath: /usr/local/files/    #/usr/local/files/  图片存储的地址
    imageUrl:  /usr/local/files/  #  图片展示路径
  soap:
    soapUrl: http://10.1.16.55/SPH_KDL_SAP/ProxyServices/QFF/ZCHN_FM_QFF_PS?wsdl       #http://10.1.225.155/SPH_KDL_SAP/ProxyServices/QFF/ZCHN_FM_QFF_PS?wsdl

