server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
spring:
  profiles:
    active: dev

  thymeleaf:
    cache: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.neefull.fsp.api.entity
  global-config:
    id-type: 0
    field-strategy: 2
    capital-mode: true
    refresh-mapper: true

logging:
  config:classpath:log4j2.xml

cardBankApi: https://ccdcapi.alipay.com/validateAndCacheCardInfo.json?cardNo=#cardNo#&cardBinCheck=true
